### ISSUE TITLE
Adição no Authors

### ISSUE THREAD

**Issue by eilins** [eilins/discreta07grp02#1]
Galera, quem criar o authors, adicione apenas seu nome e seu e-mail. Assim que forem sendo adicionados, comentem aqui.

**Comment by guidoferrario** [comment]
Criei e adicionei meu nome e email.

**Comment by flavioduart** [comment]
Adicionei!

**Comment by wesleysilas** [comment]
Adicionei!

**Comment by thiagooqueiroz** [comment]
Adicionei !

**Comment by guidoferrario** [comment]
Acredito que todos adicionaram suas informações.
