### ISSUE TITLE
REGRAS???

### ISSUE THREAD

**Issue by wesleysilas** [eilins/discreta07grp02#11]
Preciso da ajuda de vocês para saber quais as regras para passar de uma AFND para uma AFD, 
tipo um passo a passo...
chegamos nesse estágio do processamento...
heeelppp

**Comment by guidoferrario** [comment]
Pelo que eu estudei e pesquisei acho que é assim. 

1. Tomar o diagrama da transição do AFND e criar para cada conjunto de estados um novo estado onde o rótulo é o próprio conjunto.
2. Completar as transições de cada novo estado acompanhando o comportamento de cada estado individualmente e tomando a união dos estados acessados. 
3. Adicionar como estados finais aqueles estados que têm como rótulo um estado final. 
4. Eliminar os estados nunca acessados a partir do estado inicial. 
5. O AFD será completado assim:
5.1. Q do AFD são os estados resultantes dos passos até esse ponto. 
5.2. O alfabeto e o estado inicial não se alteram. 
5.3. Construir o delta. 
5.4. Os estados finais são a união dos estados finais do delta resultante.

Esse texto ( http://www.dca.fee.unicamp.br/cursos/EA876/apostila/HTML/node48.html  ) também tem um conteúdo interessante que pode ajudar.

**Comment by wesleysilas** [comment]
ok, valeu guido

**Comment by flavioduart** [comment]
Isso mesmo que Guido falou

**Comment by drbeco** [comment]
Gente, eu tenho 59 repositórios, cada um com 10 pessoas, cada pessoa mandando 10 issues.

Vamos falar coisas que "acrescentam", né?

![image](https://cloud.githubusercontent.com/assets/5805111/15797013/973b0d06-29e0-11e6-8517-8f215039ec47.png)

----


## ` isso mesmo que o Guido falou ` : *já* foi dito (pelo Guido).
