### ISSUE TITLE
Prazos, discussões

### ISSUE THREAD

**Issue by eilins** [eilins/discreta07grp02#3]
Galera, atentem para o uso do github e das issues! Discussões, duvidas, comentem aqui para que haja comunicação e trabalho em conjunto. Ps. ATENTEM PARA O PRAZO DAS MILESTONES ASSOCIADAS, alias, já temos uma a ser cumprida ate o dia 07/05 (sábado).

**Comment by guidoferrario** [comment]
Acho que todos foram devidamente informados. Issue fechada.
