### ISSUE TITLE
Dados iniciais

### ISSUE THREAD

**Issue by flavioduart** [eilins/discreta07grp02#4]
Pessoal, como professor explicou em sala, devemos pedir ao usuário colocar a quíntupla, e retornar outra, após que modificar para AFD. Então vou começar botando uns printf para  recolher dados iniciais, para poder começar o processamento. :kissing:

**Comment by eilins** [comment]
Vou colocar as structs antes!! Tudo bem?

**Comment by flavioduart** [comment]
Tudo ótimo! :dart:

**Comment by eilins** [comment]
Pronto, pode começar a fazer a entrada de dados

**Comment by eilins** [comment]
Aproveitei e defini o numero maximo de transição, de estados finais e iniciais, e de letras, q ue é o alfabeto.

**Comment by flavioduart** [comment]
Feito
