### ISSUE TITLE
Problema na leitura.

### ISSUE THREAD

**Issue by wesleysilas** [eilins/discreta07grp02#8]
Quando eu tenho uma entrada e necessito ir para dois estados ao mesmo tempo, não há opção no código para fazer isso.

**Comment by flavioduart** [comment]
Então fez ter

**Comment by wesleysilas** [comment]
oiaaa... kkkkk
estou trabalhando nisso

**Comment by wesleysilas** [comment]
Problema resolvido no commit: 6c39fc2
